### PR TITLE
Use aurelia-config

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@doktordirk Conflict

**Comment by doktordirk** [comment]
need a sec to ensure it's working after all those merges

**Comment by doktordirk** [comment]
@RWOverdijk this merge is now needed for fixing. works unbundled, but don't deploy yet though. that needs some adjustments as well afaik

**Comment by RWOverdijk** [comment]
ack

**Pull request merged**
