### PR TITLE
feat(project): add language, footer and hide user badge

### PR DESCRIPTION
**Pull request by RWOverdijk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@doktordirk Any idea why translations seem to not work properly?

**Comment by doktordirk** [comment]
not yet

**Comment by RWOverdijk** [comment]
Ah alright. By the way, I'm really digging this new preview environment stuff. It's awesome!

**Comment by doktordirk** [comment]
i guess so, just that i still don't know where each pr is located. it's not https://deploy-preview-41--governor-polecat-62631.netlify.com/#/login appatenty

**Comment by RWOverdijk** [comment]
@doktordirk It's https://deploy-preview-41--swan-example.netlify.com/

I renamed it. But you can also click on the green checkmark ^ that links to the example. I'll enable preview comments.

**Comment by doktordirk** [comment]
nifty!

**Comment by RWOverdijk** [comment]
Deploy preview ready!

Built with commit 57812b82cb3fbb8e5633b50ac5f81892a1829831

https://deploy-preview-41--swan-example.netlify.com

**Comment by RWOverdijk** [comment]
@doktordirk From now on, these comments will be added to make it easier ^

**Comment by doktordirk** [comment]
ups, how did it add my PR.? but well

**Comment by RWOverdijk** [comment]
@doktordirk You pushed to my branch haha

**Comment by RWOverdijk** [comment]
@doktordirk Doesn't work for me.  (same behavior, english remains)

**Comment by doktordirk** [comment]
this one did

**Comment by RWOverdijk** [comment]
AWESOME!

**Pull request merged**
