### PR TITLE
Update checkbox.html

### PR DESCRIPTION
**Pull request by bzd2000**
See issue #47

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Deploy preview failed.

Built with commit fe3b25354c2b888f8cb4b4884ddf24134fd5e4cb

https://app.netlify.com/sites/swan-example/deploys/5866345e66867464449d0295

**Comment by bzd2000** [comment]
I guess I did something wrong, but I don't have access to your netlitfy build log to check it

**Comment by RWOverdijk** [comment]
I think this might be broken due to the latest tools. @VMBindraban could you look into this?

**Comment by VMBindraban** [comment]
Babel issue, fixed in https://github.com/SpoonX/swan-example-client/pull/49

**Pull request closed without merging**
