### PR TITLE
fix(project): Added jspm_packages to dist

### PR DESCRIPTION
**Pull request by RWOverdijk**
fix(project): Added jspm_packages to dist

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@VMBindraban Review :)

**Comment by doktordirk** [comment]
don'T just wanna not gitignore the folder? 

particularly since i've added more stuff in there

**Comment by RWOverdijk** [comment]
@doktordirk no, because the normal dir shouldn't be in version control. Just this one :)

EDIT: Never mind. I forgot to commit the file.

**Comment by doktordirk** [comment]
:+1:

**Pull request merged**
