### PR TITLE
feat(form): example using list entities

### PR DESCRIPTION
**Pull request by bas080**
uses a custom schema to render a collection of list entities

NOTE: requires a new build of aurelia-form.

### CODE REVIEW

**Comment by doktordirk** [comment]
all todos appear in the first list for for me

**Comment by bas080** [comment]
Visually there is one list. It has a string input for the todo text. checkbox for done state and an association select for the list it is in.

**Comment by doktordirk** [comment]
rephrasing: the wrong list is selected on loading

**Comment by bas080** [comment]
You mean in the association select. That is because form is not yet published and updated.

**Comment by doktordirk** [comment]
it is (published and hence updated on my test version)

**Pull request merged**
